# Changes here will be overwritten by Copier
_commit: fdc7a96
_src_path: gh:34j/pypackage-template-fork
add_me_as_contributor: false
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: false
open_source_license: MIT
open_with_vscode: false
package_name: cached_historical_data_fetcher
project_name: Cached Historical Data Fetcher
project_short_description: Python utility for fetching any historical data using caching.
project_slug: cached-historical-data-fetcher
run_poetry_install: false
setup_github: false
setup_pre_commit: false
setup_venv: false
venv_version: '3.10'

