blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/34j/cached-historical-data-fetcher/discussions/categories/q-a
    about: Please ask and answer questions here.
